### ISSUE TITLE
数据库迁移报错

### ISSUE THREAD

**Issue by 1760714192** [mowangjuanzi/article#1]
![2019-07-07 21-25-46屏幕截图](https://user-images.githubusercontent.com/41221992/60769052-0525a000-a0fe-11e9-8b0e-c8afb0a2ff58.png)

**Comment by mowangjuanzi** [comment]
mysql 哪个版本？

**Comment by mowangjuanzi** [comment]
https://learnku.com/articles/4195/laravel-54-common-error-specified-key-was-too-long

你可以参考这篇文章来解决

**Comment by 1760714192** [comment]
> mysql 哪个版本？

5.5

**Comment by mowangjuanzi** [comment]
拉取最新最新代码重新执行迁移即可

**Comment by 1760714192** [comment]
已解决， 还有就是无默认用户以及无法注册

**Comment by mowangjuanzi** [comment]
我已经新增了命令可以初始化用户。至于用户注册。我暂时还没想好。所以就不会默认开启注册
